# Generated by Django 5.0.6 on 2024-07-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_borrowrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='borrower_name',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_app.student'),
        ),
    ]
